# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Las rutas de Alberto
email: aldolo.vlc@gmail.com

favicons: /favicons
img: /img
featured: featured.jpg
description: >
  Por ahora iremos poniendo unas cuantas rutas y un par de páginas. Nada demasiado grande.
  La intención es probar.
baseurl: "" # En teoría estará en el directorio raíz de un subdominio
url: "" # Mientras sea para probar, nada. También podremos cambiar el hosts del ordenador.
facebook: {id_user: "1475674066", id_api: "268083790276958", autor: aldolo}
twitter: {site: aldolo, card: summary_large_image, autor: aldolo}
autor: "Alberto Domínguez"

#Los banners deberían ser de 1260x240
banners: [banner1.jpg, banner2.jpg]

menu:
- texto: Sobre mí
  url: /sobre-mi.html
- texto: Carretera
  url: /carretera/
- texto: Btt
  url: /btt/
- texto: Viajes
  url: /btt/
- texto: Consejos
  url: /consejos.html

twitter_username: aldolo
github_username:  fuera

disqus:
- shortname: nuevoelperroverdebttes

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
